# Site settings
title: Rafi Khan
description: 'My Blog'
url: 'http://z3t0.github.io'
baseurl: '/'
google_analytics: 'UA-60577106-3'

author:
  name: 'Rafi Khan'
  email: zetoslab@gmail.com
  twitter_username: Z3T0_rk
  github_username:  z3t0

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
